development:
  adapter: postgresql
  encoding: utf8
  database: use_rabl_development
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: use_rabl_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: use_rabl
  pool: 5